### ISSUE TITLE
PDFviewer broken in VS Code 1.47.0 over remote ssh

### ISSUE THREAD

**Issue by thegregyang** [James-Yu/LaTeX-Workshop#2206]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

The PDFviewer does not display the PDF in VS Code 1.47.0 over remote ssh.

### To Reproduce

1. Open a latex project on a remote server via remote ssh plugin
2. Click on the "View Latex PDF file" button
3. A new tab opens but nothing is displayed

### Expected behavior

The pdf file should be displayed in the new tab.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[01:53:41] Initializing LaTeX Workshop.
[01:53:41] Creating PDF file watcher.
[01:53:41] Creating LaTeX Workshop http and websocket server.
[01:53:41] LaTeX Workshop initialized.
[01:53:41] Found root file of this subfile from active editor: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/main.tex
[01:53:41] Root file changed: from undefined to /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/main.tex
[01:53:41] Start to find all dependencies.
[01:53:41] Instantiating a new file watcher for /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/main.tex
[01:53:41] Creating Bib file watcher.
[01:53:41] Parsing a file and its subfiles: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/main.tex
[01:53:41] Parsing a file and its subfiles: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/NetsortTMain.tex
[01:53:41] Parse fls file.
[01:53:41] Cannot find fls file: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/NetsortTMain.fls
[01:53:41] Parsing a file and its subfiles: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/semicircleLaw.tex
[01:53:41] Parse fls file.
[01:53:41] Cannot find fls file: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/semicircleLaw.fls
[01:53:41] Parsing a file and its subfiles: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/FreeIndependence.tex
[01:53:41] Parse fls file.
[01:53:41] Fls file found: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/FreeIndependence.fls
[01:53:41] Parse aux file: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/FreeIndependence.aux
[01:53:41] Parsing a file and its subfiles: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/proofsketch.tex
[01:53:41] Parse fls file.
[01:53:41] Cannot find fls file: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/proofsketch.fls
[01:53:41] Parsing a file and its subfiles: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/extraTheorems.tex
[01:53:41] Parse fls file.
[01:53:41] Cannot find fls file: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/extraTheorems.fls
[01:53:41] Parsing a file and its subfiles: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/Generalized_GP4A_NTK4A.tex
[01:53:41] Parse fls file.
[01:53:41] Cannot find fls file: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/Generalized_GP4A_NTK4A.fls
[01:53:41] Parsing a file and its subfiles: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/advancedNetsorT.tex
[01:53:41] Parse fls file.
[01:53:41] Cannot find fls file: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/advancedNetsorT.fls
[01:53:41] Parsing a file and its subfiles: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/proofs.tex
[01:53:41] Parse fls file.
[01:53:41] Cannot find fls file: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/proofs.fls
[01:53:41] Found .bib file: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/references.bib
[01:53:41] Added to bib file watcher: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/references.bib
[01:53:41] Parsing .bib entries from /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/references.bib
[01:53:41] Parse fls file.
[01:53:41] Cannot find fls file: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/main.fls
[01:53:41] Server created on 127.0.0.1:46137
[01:53:41] Added to file watcher: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/main.tex
[01:53:41] Added to file watcher: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/NetsortTMain.tex
[01:53:41] Added to file watcher: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/semicircleLaw.tex
[01:53:41] Added to file watcher: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/FreeIndependence.tex
[01:53:41] Added to file watcher: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/proofsketch.tex
[01:53:41] Added to file watcher: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/extraTheorems.tex
[01:53:41] Added to file watcher: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/Generalized_GP4A_NTK4A.tex
[01:53:41] Added to file watcher: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/advancedNetsorT.tex
[01:53:41] Added to file watcher: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/proofs.tex
[01:53:41] Snippet data loaded.
[01:53:41] LaTeX Workshop version: 8.11.1
[01:53:41] Parsed 1132 bib entries from /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/references.bib.
[01:55:01] VIEW command invoked with mode: file:///home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/FreeIndependence.tex.
[01:55:01] Found root file of this subfile from active editor: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/main.tex
[01:55:01] Keep using the same root file: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/main.tex.
[01:55:01] Serving PDF file at http://localhost:46137/viewer.html?file=pdf..JTJGaG9tZSUyRmdyZWd5YW5nJTJGc2FtYmFzaGFyZSUyRnRleC13b3Jrc3BhY2UlMkZUZW5zb3JQcm9ncmFtRnVsbFBvd2VyJTJGRnJlZUluZGVwZW5kZW5jZS5wZGY
[01:55:01] The encoded path is /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/FreeIndependence.pdf
[01:55:01] Open PDF tab for /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/FreeIndependence.pdf
[01:55:01] Found root file of this subfile from active editor: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/main.tex
[01:55:01] Keep using the same root file: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/main.tex.
[01:55:15] Found root file of this subfile from active editor: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/main.tex
[01:55:15] Keep using the same root file: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/main.tex.
[01:55:16] VIEW command invoked with mode: file:///home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/FreeIndependence.tex.
[01:55:16] Found root file of this subfile from active editor: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/main.tex
[01:55:16] Keep using the same root file: /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/main.tex.
[01:55:16] Serving PDF file at http://localhost:46137/viewer.html?file=pdf..JTJGaG9tZSUyRmdyZWd5YW5nJTJGc2FtYmFzaGFyZSUyRnRleC13b3Jrc3BhY2UlMkZUZW5zb3JQcm9ncmFtRnVsbFBvd2VyJTJGRnJlZUluZGVwZW5kZW5jZS5wZGY
[01:55:16] The encoded path is /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/FreeIndependence.pdf
[01:55:16] Open PDF tab for /home/gregyang/sambashare/tex-workspace/TensorProgramFullPower/FreeIndependence.pdf
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

workbench.desktop.main.js:sourcemap:266 [Extension Host] (node:19832) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ workbench.desktop.main.js:sourcemap:266
workbench.desktop.main.js:sourcemap:1670   ERR Cannot read property 'state' of undefined: TypeError: Cannot read property 'state' of undefined
	at PdfViewerPanelSerializer.deserializeWebviewPanel (/home/gregyang/.vscode-server/extensions/james-yu.latex-workshop-8.11.1/out/src/components/viewer.js:64:30)
	at K.$deserializeWebviewPanel (/home/gregyang/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/out/vs/server/remoteExtensionHostProcess.js:805:485)
	at m._doInvokeHandler (/home/gregyang/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/out/vs/server/remoteExtensionHostProcess.js:823:683)
	at m._invokeHandler (/home/gregyang/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/out/vs/server/remoteExtensionHostProcess.js:823:375)
	at m._receiveRequest (/home/gregyang/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/out/vs/server/remoteExtensionHostProcess.js:822:14)
	at m._receiveOneMessage (/home/gregyang/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/out/vs/server/remoteExtensionHostProcess.js:821:6)
	at /home/gregyang/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/out/vs/server/remoteExtensionHostProcess.js:819:34
	at l.fire (/home/gregyang/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/out/vs/server/remoteExtensionHostProcess.js:45:801)
	at v.fire (/home/gregyang/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/out/vs/server/remoteExtensionHostProcess.js:235:849)
	at /home/gregyang/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/out/vs/server/remoteExtensionHostProcess.js:997:744
	at l.fire (/home/gregyang/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/out/vs/server/remoteExtensionHostProcess.js:45:801)
	at v.fire (/home/gregyang/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/out/vs/server/remoteExtensionHostProcess.js:235:849)
	at t.PersistentProtocol._receiveMessage (/home/gregyang/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/out/vs/server/remoteExtensionHostProcess.js:240:276)
	at /home/gregyang/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/out/vs/server/remoteExtensionHostProcess.js:237:357
	at l.fire (/home/gregyang/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/out/vs/server/remoteExtensionHostProcess.js:45:801)
	at p.acceptChunk (/home/gregyang/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/out/vs/server/remoteExtensionHostProcess.js:233:393)
	at /home/gregyang/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/out/vs/server/remoteExtensionHostProcess.js:232:753
	at Socket.t (/home/gregyang/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/out/vs/server/remoteExtensionHostProcess.js:241:826)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
workbench.desktop.main.js:sourcemap:1670   ERR read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
```

## Desktop [Required]
 - OS:  Windows 10
 - VS Code version: 1.47.0
 - Extension version: 8.11.1
 - TeX distribution version: TeX Live 2019

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

Yes

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote SSH
- Remote Extension Version: 0.51.0

**Comment by tamuratak** [comment]
Might be related:

- microsoft/vscode-remote-release/issues/3362
- microsoft/vscode/issues/102449

**Comment by guitsilva** [comment]
Same issue with **Remote Container** (Docker). Strangely, as reported at the VSCode issues mentioned above, the following workaround solves the issue:

1) Open a browser preview: "LaTeX-Workshop side panel" -> "Commands" -> "View LaTeX PDF" -> "View in web browser".

2) Close the browser preview. 

3) Open a VSCode tab preview: "LaTeX-Workshop side panel" -> "Commands" -> "View LaTeX PDF" -> "View in VSCode tab".

This workaround is a just a **palliative** and only fix the problem until you restart VSCode.

**Comment by GeckoEidechse** [comment]
Can confirm that the workaround @guitsilva mentioned also works for **Remote SSH**.

**Comment by rohitgirdhar** [comment]
Facing the same issue. The solution by @guitsilva was working for me earlier, but since last couple of days when try that, I get the following tab that asks for a password to open the file
![image](https://user-images.githubusercontent.com/1893429/90063760-de01b080-dcb7-11ea-9d33-523e4966449c.png)

**Comment by James-Yu** [comment]
I can reproduce. It seems to be a vscode webview+remote dev bug. Also see https://github.com/Ikuyadeu/vscode-R/issues/380

**Comment by CheariX** [comment]
In 1.48, the behavior got worse.
Opening does not work out of the box, still.
But when using the browser-work-around, the PDF is not rendered. I just see strange buttons and text :(

**Comment by CheariX** [comment]
I could _fix_ the bug in 1.47.3 by applying the following config to `devcontainer.json`:

```json
{
   ...
  "forwardPorts": [ 35556 ],
  "settings": {
     "latex-workshop.viewer.pdf.internal.port": 35556,
    ...
  },
}
```

I guess the problem occurs due to the default value `"0"` of the property `latex-workshop.viewer.pdf.internal.port`.
Either because it is randomly chosen, or because it is a string instead of a number?

**Comment by tamuratak** [comment]
Tracked in microsoft/vscode/issues/102449

**Comment by pablo-de-andres** [comment]
I get the same issue when using WSL (2)

**Comment by st-red-strat** [comment]
I have the same issue when using WSL1.
I used to reinstall older versions before and it worked, but now installing older versions does no longer work.

**Comment by Sseh** [comment]
Please make sure you are not using a space bar in your .tex files. that might be what's causing the issue

**Comment by Imkaidu** [comment]
I think it works now due to the update of the VS code?

**Comment by LamKat** [comment]
I've encountered the same bug. I'm using WSL with Ubuntu. 

It seems that maybe VSCode is blocking some of the files from loading because they break the content security policy. I'm drawn to this conclusion from the following error logs produced when opening the internal (VSCode tab) viewer

``` 
[Embedded Page] Refused to load the stylesheet 'http://127.0.0.1:57557/viewer.css' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline'". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

[Embedded Page] Refused to load the stylesheet 'http://127.0.0.1:57557/latexworkshop.css' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline'". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

[Embedded Page] Refused to load the script 'http://127.0.0.1:57557/build/pdf.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

[Embedded Page] Refused to load the script 'http://127.0.0.1:57557/out/viewer/latexworkshop.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

[Embedded Page] Refused to load the script 'http://127.0.0.1:57557/viewer.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

**Comment by tamuratak** [comment]
FYI. You can downgrade to VS Code 1.46 with binaries in this page:

- https://code.visualstudio.com/updates/v1_46

**Comment by BerriJ** [comment]
The related issue was fixed today. 😊
I'll test the insiders build later.

**Comment by sfolje0** [comment]
Hey, BerriJ, what does this mean practically. When will I have fixed version on my machine? Best regards.

**Comment by BerriJ** [comment]
Well it's not entirely clear to me but the linked issue is tagges as "insiders-released" now. So the very next insiders build will include this fix.

Furthermore, you can track the upcoming changes in 1.49 [here](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_49.md). But 1.49 will be released on 2020-09-12.

**Comment by BerriJ** [comment]
PDF Preview is working again for me with the latest insiders build (snap).

![image](https://user-images.githubusercontent.com/37799358/91690498-58f71200-eb66-11ea-8fe8-4584c05c7446.png)

**Comment by grishagin** [comment]
Same VSCode Insiders 1.49.0.  
PDF Preview is still not working for me.

**Comment by Queuecumber** [comment]
I also have insiders 1.49.0 and the pdf viewer isnt working for me (local not ssh)

**Comment by wkjung** [comment]
Same issue here with 1.48.

**Comment by BerriJ** [comment]
I investigated a little bit today because you all have problems and for me it's working fine.
I'm using the following devcontainer.json

```
{
	"name": "Paper",
	"image": "berrij/devenv:dev",
	"initializeCommand": "docker pull berrij/devenv:dev",
	"runArgs": [
		"--rm",
		"--net",
		"host"
	],
	// Extensions will get installed automatically
	"extensions": [
		// Latex
		"james-yu.latex-workshop",
		"znck.grammarly"
	],
	// Set *default* container specific settings
	"settings": {
		// Latex
		"latex-workshop.view.pdf.viewer": "tab",
		// Format code as you type, paste or save
		"editor.formatOnPaste": true,
		"editor.formatOnType": true,
		"editor.formatOnSave": true
	}
}
```

You could try this for yourself. It's all in a public [repo](https://github.com/BerriJ/devenv). But make sure to use at least VS-Code Insiders from 2020-08-28 or newer...

**Comment by Queuecumber** [comment]
It seems like its working again for me after the latest 1.49 insider

**Comment by tamuratak** [comment]
You can downgrade to VS Code 1.46 with binaries in the release note:

- https://code.visualstudio.com/updates/v1_46

If you want this issue fixed soon, please upvote microsoft/vscode/issues/102449. This issue will not be fixed in the next release, VS Code 1.49. It will be fixed in VS Code 1.50 or later.

We can do nothing on our side as far as I tried.

**Comment by bwegge** [comment]
(fyi) VS Code 1.49 was just released, and so far PDF preview has been working fine again (at least for connections into WSL2).

**Comment by Blaok** [comment]
For remote ssh it works but only after I set up port forwarding manually or by clicking "View in web browser".

**Comment by bwegge** [comment]
> For remote ssh it works but only after I set up port forwarding manually or by clicking "View in web browser".
There was also some update for the remote extensions related to "Automatically forward ports":
https://github.com/microsoft/vscode-docs/blob/master/remote-release-notes/v1_49.md
Maybe this is also required?

**Comment by grishagin** [comment]
> 
> 
> (fyi) VS Code 1.49 was just released, and so far PDF preview has been working fine again (at least for connections into WSL2). There also was some [update for the remote extensions](https://github.com/microsoft/vscode-docs/blob/master/remote-release-notes/v1_49.md) related to "Automatically forward ports", which might actually remedy the issue.

Indeed, it works for me again on VS Code 1.49.0-insider + WSL2.

**Comment by bersbersbers** [comment]
I am still seeing this issue in v1.49.1 with Remote SSH v0.55.0.

> For remote ssh it works but only after I set up port forwarding manually or by clicking "View in web browser".

May I ask how you did that? Did you just enable "port forwarding" somewhere, or did you have to set up specific ports?

**Comment by Blaok** [comment]
> I am still seeing this issue in v1.49.1 with Remote SSH v0.55.0. Same on today's insiders 1.50.0 with the same Remote SSH.
> 
> > For remote ssh it works but only after I set up port forwarding manually or by clicking "View in web browser".
> 
> May I ask how you did that? Did you just enable "port forwarding" somewhere, or did you have to set up specific ports?

Sure, there are two different ways to do the same thing (i.e., set up port forwarding), so choose only one of them:

1. Manual setup: follow instructions [here][1]. The key is to choose the correct port to forward. Usually the one listened by `/home/<username>/.vscode-server/bin/.../node` is the one to go.
2. Open preview in browser: follow instructions [here][2]. Somehow doing so sets up the port forwarding automatically.

[1]: https://code.visualstudio.com/docs/remote/ssh#_temporarily-forwarding-a-port
[2]: https://github.com/James-Yu/LaTeX-Workshop/issues/2206#issuecomment-659042978

**Comment by bersbersbers** [comment]
@Blaok:

> The key is to choose the correct port to forward. 

Sure - how to do that was my question, actually ;)

> Usually the one listened by `/home/<username>/.vscode-server/bin/.../node` is the one to go.

This is a binary that presents some terminal when run - what do you mean by "listed by `node`"?

Anyway, it seems that port is changing every time I restart VS Code, so there is not really a way to set this up once and for all. I'll have to go with the preview method then.

**Comment by Infinemen** [comment]
1. If I close the PDF tab before I exit vscode, then next time I can preview PDF in vscode. Everything works for me. 

2. If I forget close the PDF tab before I exit vscode, next time when I open vscode, the PDF tab will be there but no pdf showing. And I can not preview PDF any more.

**Comment by bersbersbers** [comment]
This is still an issue with VS Code and VS Code Remote SSH 1.52.0, despite recent improvements on their side:
> On linux remotes, ports are now forwarded automatically by detecting new processes that are listening on a port. This is an improvement over the old behavior (**watching the terminal and debug output for strings that looked like addresses**) because it will find more ports to forward.

https://github.com/microsoft/vscode-docs/blob/master/remote-release-notes/v1_52.md#port-forwarding

Note that https://github.com/microsoft/vscode/issues/102449 is still open, but a workaround that seems to work for some of them there https://github.com/microsoft/vscode/issues/102449#issuecomment-713675008 is to output addresses into the terminal, which will then be picked up in line with what I highlighted in the quote above. Maybe this is possible for LaTeX Workshop, too?

Finally, and most importantly, https://github.com/James-Yu/LaTeX-Workshop/issues/2206#issuecomment-674092455 by @CheariX is severely underrated, as it applies to Remote SSH, too. Just put

```json
"latex-workshop.viewer.pdf.internal.port": 35556,
```

in your `settings.json`, and configure your SSH session to forward that port - e.g., in your ssh config:
```
Host your_server_name
    LocalForward 35556 localhost:35556
```
(You can pick any other port - just be consistent.)

After months of suffering, this has solved the issue for me, in both use cases that @Infinemen describes in https://github.com/James-Yu/LaTeX-Workshop/issues/2206#issuecomment-718458386

**Comment by nd-02110114** [comment]
When will you release the next version...? I'm having trouble with this problem because it happens so often...
